# Generated by Django 5.2.7 on 2025-10-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('threat_type', models.CharField(choices=[('MALWARE', 'Malware'), ('PHISHING', 'Phishing'), ('RANSOMWARE', 'Ransomware'), ('ACCESO_NO_AUTORIZADO', 'Acceso no autorizado'), ('DOS', 'Ataque DoS'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('criticality', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
