# Generated by Django 6.0 on 2026-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_virustotal_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='gemini_analysis',
            field=models.JSONField(blank=True, help_text='Análisis contextual generado por Gemini (explicación de patrones)', null=True),
        ),
    ]
